name: Master
on:
  push:
    branches:
      - main
jobs:
  sync_data:
    name: Sync data
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_SEARCH_ADMIN_KEY: ${{ secrets.ALGOLIA_SEARCH_ADMIN_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install Dependencies
        run: npm install

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Sync Algolia search
        run: ts-node ./scripts/sync-algolia

      - name: Sync posts
        run: ts-node ./scripts/sync-posts

      - name: Sync collections
        run: ts-node ./scripts/sync-collections
