name: Master
on:
  pull_request:
    types:
      - closed
      - opened
    branches:
      - master
jobs:
  sync_data:
    name: Sync data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install Dependencies
        run: npm install

      - name: Sync Algolia search
        run: ts-node ./scripts/sync-algolia

      - name: Sync posts
        run: ts-node ./scripts/sync-posts

      - name: Sync collections
        run: ts-node ./scripts/sync-collections
